<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>A semi-automatic radio creator for The Crew.</Description>
    
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.08</Version>
    <Authors>FTIW</Authors>
	  <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="Gibbed.Dunia2\Gibbed.Dunia2.FileFormats\Gibbed.Dunia2.FileFormats.csproj" />
	  
    <None Include="Assets\**\*.*">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
	  
    <Compile Remove="Gibbed.Dunia2\**" />
    <EmbeddedResource Remove="Gibbed.Dunia2\**" />
    <None Remove="Gibbed.Dunia2\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.7" />
  </ItemGroup>

</Project>
